#!/usr/bin/env ruby
#^syntax detection
#site 'http://community.opscode.com/api/v1'


cookbook "zookeeper",
  :git => "https://github.com/infochimps-labs/ironfan-pantry/tree/master/cookbooks"
  #:ref => "v0.7.1"

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
