name    'zookeeper-puppet'
version '0.1.0'
source 'UNKNOWN'
author 'matlockx'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'puppetlabs/java', '>= 1.0.1'
